name: Deploy API

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    # This allows manual triggering from GitHub Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: 20.62.249.125
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Create directory structure
            mkdir -p ~/simple-api
            
            # Create app.py file
            cat > ~/simple-api/app.py << 'EOL'
            from flask import Flask, jsonify

            app = Flask(__name__)

            @app.route('/sayHello', methods=['GET'])
            def say_hello():
                return jsonify({"message": "Hello User."})

            if __name__ == '__main__':
                app.run(host='0.0.0.0', port=80, debug=False)
            EOL
            
            # Create requirements.txt file
            cat > ~/simple-api/requirements.txt << 'EOL'
            flask==2.0.1
            werkzeug==2.0.3
            gunicorn==20.1.0
            EOL
            
            # Display Python version
            echo "Python version:"
            python3 --version
            
            # Setup virtual environment
            cd ~/simple-api
            if [ ! -d "venv" ]; then
              echo "Creating new virtual environment..."
              python3 -m venv venv
            else
              echo "Using existing virtual environment..."
            fi
            
            # First activate the virtual environment
            echo "Activating virtual environment..."
            source venv/bin/activate
            
            # Verify Python path
            echo "Python path: $(which python)"
            
            # Then install dependencies in the activated environment
            echo "Installing dependencies..."
            pip install -r requirements.txt
            
            # Check if port 80 is in use
            echo "Checking if port 80 is in use:"
            sudo netstat -tulpn | grep :80 || echo "Port 80 is free"
            
            # Kill any existing application
            echo "Stopping any existing application..."
            sudo pkill -f "python3 app.py" || echo "No existing app running"
            
            # Run application with full path and verbose output
            echo "Starting application..."
            sudo nohup $(which python) app.py > app.log 2>&1 &
            echo "App started with PID: $!"
            
            # Wait for app to start
            echo "Waiting for app to start..."
            sleep 5
            
            # Check if app is running
            echo "Checking running Python processes:"
            ps aux | grep python
            
            # Verify app log output
            echo "Checking app log:"
            tail -n 20 app.log
            
            # Verify deployment
            echo "Testing API response:"
            curl -v http://localhost/sayHello 
