name: Deploy API

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VM
        run: |
          # Add VM host key
          mkdir -p ~/.ssh
          ssh-keyscan -H 20.62.249.125 >> ~/.ssh/known_hosts
          
          # Clean up and create directory
          ssh azureuser@20.62.249.125 'sudo rm -rf ~/simple-api && mkdir -p ~/simple-api'
          
          # Copy app files (without .git)
          scp app.py requirements.txt azureuser@20.62.249.125:~/simple-api/
          
          # Setup and run application
          ssh azureuser@20.62.249.125 'cd ~/simple-api && \
            sudo apt-get update && \
            sudo apt-get install -y python3-pip && \
            sudo pip3 install -r requirements.txt && \
            sudo pkill -f "python3 app.py" || true && \
            sudo nohup python3 app.py > app.log 2>&1 &'
          
          echo "Deployment completed. App should be running on port 80."
          
          # Verify deployment after a brief wait
          sleep 10
          ssh azureuser@20.62.249.125 'curl -s http://localhost/sayHello || echo "API not responding on port 80"' 
