# Disabled old workflow
# This file has been replaced by simple_deploy.yml 

name: Deploy API

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: 20.62.249.125
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/simple-api
            echo "Directory created"
      
      - name: Copy files
        uses: appleboy/scp-action@master
        with:
          host: 20.62.249.125
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "app.py,requirements.txt"
          target: "~/simple-api"
      
      - name: Run app
        uses: appleboy/ssh-action@master
        with:
          host: 20.62.249.125
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/simple-api
            # Install required system packages
            sudo apt-get update
            sudo apt-get install -y python3-pip python3-venv
            
            # Create and activate virtual environment
            python3 -m venv venv
            source venv/bin/activate
            
            # Install requirements in the virtual environment
            pip install -r requirements.txt
            
            # Stop any running instances
            sudo pkill -f "python3 app.py" || true
            
            # Run the application with sudo (needed for port 80)
            sudo nohup $(which python3) app.py > app.log 2>&1 &
            
            # Verify the app is running
            echo "Waiting for app to start..."
            sleep 5
            curl -s http://localhost/sayHello || echo "API not responding on port 80" 
