# Disabled old workflow
# This file has been replaced by simple_deploy.yml 

name: Deploy API

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: 20.62.249.125
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/simple-api
            echo "Directory created"
      
      - name: Copy files
        uses: appleboy/scp-action@master
        with:
          host: 20.62.249.125
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "app.py,requirements.txt"
          target: "~/simple-api"
      
      - name: Run app
        uses: appleboy/ssh-action@master
        with:
          host: 20.62.249.125
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/simple-api
            sudo apt-get update
            sudo apt-get install -y python3-pip
            sudo pip3 install -r requirements.txt
            sudo pkill -f "python3 app.py" || true
            sudo nohup python3 app.py > app.log 2>&1 & 
