name: Deploy API

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test SSH Connection
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 20.62.249.125 >> ~/.ssh/known_hosts
          ssh -o BatchMode=yes -o StrictHostKeyChecking=no -v azureuser@20.62.249.125 "echo 'SSH connection successful'"

      - name: Create Directory
        if: success()
        run: |
          ssh azureuser@20.62.249.125 "mkdir -p ~/simple-api"
          echo "Directory created"

      - name: Copy App File
        if: success()
        run: |
          scp -v app.py azureuser@20.62.249.125:~/simple-api/
          echo "App file copied"

      - name: Copy Requirements File
        if: success()
        run: |
          scp -v requirements.txt azureuser@20.62.249.125:~/simple-api/
          echo "Requirements file copied"

      - name: Debug info
        run: |
          echo "Current directory:"
          pwd
          echo "Files to deploy:"
          ls -la
          echo "SSH agent status:"
          ssh-add -l
          echo "User info:"
          whoami

      - name: Add VM host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 20.62.249.125 >> ~/.ssh/known_hosts
          echo "Added host key"

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -o BatchMode=yes azureuser@20.62.249.125 echo "SSH connection successful"

      - name: Clean up remote directory
        run: |
          ssh azureuser@20.62.249.125 'sudo rm -rf ~/simple-api && mkdir -p ~/simple-api'
          echo "Directory cleared"

      - name: Install dependencies
        run: |
          ssh azureuser@20.62.249.125 'cd ~/simple-api && sudo apt-get update && sudo apt-get install -y python3-pip'
          echo "Dependencies installed"

      - name: Install Python packages
        run: |
          ssh azureuser@20.62.249.125 'cd ~/simple-api && sudo pip3 install -r requirements.txt'
          echo "Python packages installed"

      - name: Run application
        run: |
          ssh azureuser@20.62.249.125 'cd ~/simple-api && sudo pkill -f "python3 app.py" || true && sudo nohup python3 app.py > app.log 2>&1 &'
          echo "Application started"

      - name: Verify deployment
        run: |
          sleep 10
          ssh azureuser@20.62.249.125 'curl -s http://localhost/sayHello || echo "API not responding on port 80"' 
