# Disabled old workflow
# This file has been replaced by simple_deploy.yml 

name: Deploy API

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup remote directory
        uses: appleboy/ssh-action@master
        with:
          host: 20.62.249.125
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ -d "~/simple-api/.git" ]; then
              rm -rf ~/simple-api/.git
            fi

      - name: Copy files
        uses: appleboy/scp-action@master
        with:
          host: 20.62.249.125
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "app.py,requirements.txt"
          target: "~/simple-api"
          overwrite: true
      
      - name: Run application
        uses: appleboy/ssh-action@master
        with:
          host: 20.62.249.125
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/simple-api
            
            # Check if venv exists, if not create it
            if [ ! -d "venv" ]; then
              echo "Creating new virtual environment..."
              python3 -m venv venv
            fi
            
            # Ensure pip is installed in the venv
            source venv/bin/activate
            pip install -r requirements.txt
            
            # Kill any existing instances and start the application
            sudo pkill -f "python3 app.py" || true
            sudo nohup $(which python3) app.py > app.log 2>&1 &
            
            echo "API running on port 80"
            echo "Testing API..."
            sleep 3
            curl -s http://localhost/sayHello 
