name: Simple Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 20.62.249.125
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Creating directory..."
            mkdir -p ~/simple-api
            echo "Directory created"
      
      - name: Upload files
        uses: appleboy/scp-action@master
        with:
          host: 20.62.249.125
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "app.py,requirements.txt"
          target: "~/simple-api"
      
      - name: Install and run
        uses: appleboy/ssh-action@master
        with:
          host: 20.62.249.125
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Installing dependencies..."
            cd ~/simple-api
            sudo apt-get update
            sudo apt-get install -y python3-pip
            sudo pip3 install -r requirements.txt
            echo "Dependencies installed"
            
            echo "Starting application..."
            sudo pkill -f "python3 app.py" || true
            sudo nohup python3 app.py > app.log 2>&1 &
            echo "Application started"
            
            echo "Testing API..."
            sleep 5
            curl -s http://localhost/sayHello || echo "API not responding on port 80" 
