name: Deploy Test

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Debug SSH
        run: |
          echo "SSH agent status:"
          ssh-add -l
          echo "SSH directory contents:"
          ls -la ~/.ssh || mkdir -p ~/.ssh

      - name: Add host key
        run: |
          ssh-keyscan -v -H 20.62.249.125 >> ~/.ssh/known_hosts
          echo "Host key added"
          cat ~/.ssh/known_hosts

      - name: Simple SSH test
        run: |
          ssh -o BatchMode=yes -o StrictHostKeyChecking=no -v azureuser@20.62.249.125 "echo 'Connection test'"

      - name: Create directory
        if: success()
        run: |
          ssh -v azureuser@20.62.249.125 "mkdir -p ~/simple-api-test"

      - name: Copy single file
        if: success()
        run: |
          scp -v app.py azureuser@20.62.249.125:~/simple-api-test/ 
